### PR TITLE
Change the type of constants

### PR DESCRIPTION
**Pull request by ephja**

### CODE REVIEW

**Comment by Parashurama** [comment]
Awesome!
Here is few improvements.

``GLenum`` and ``GLbitfield`` really should be **distinct** types with the following procs defined somewhere:
```nim
proc `==`*(a: GLenum, b: GLenum): bool {.borrow.}

proc `==`*(a: GLbitfield, b: GLbitfield): bool {.borrow.}

proc `or`*(a: GLbitfield, b: GLbitfield): GLbitfield {.borrow.}

# also maybe for table look up:
proc hash*(a: GLenum): int = 
  ## efficient hashing of integers (taken from hashes module)
  result = x
```
You also appear to have missed constants with name like "*_BIT" being of type ``GLbitfield``

One last thing: 
Quite a few entries are defined  with no type, defaulting to **int**, they seems to be all ``Glenum``
ex:
GL_STATIC_VERTEX_ARRAY_IBM* = 103061
GL_DOUBLE_MAT3x2* = 0x8F4B
GL_SKIP_COMPONENTS3_NV* = -4
and many others

Also, what kind of script are you using to extract data from the xml specs?

**Comment by ephja** [comment]
I've fixed all the obvious mistakes. Now I just need to bump the minor version.

I wrote my own spec parser, but I don't know if I still have it.

**Comment by Parashurama** [comment]
Excellent!
both [nvidia](https://www.opengl.org/registry/specs/NV/transform_feedback.txt) [specs](https://www.opengl.org/registry/specs/ARB/transform_feedback3.txt) appears to agree with f841f41.
One minor correction; all constants of the type *BIT[0-9]_QCOM are of the wrong type.

According to [this QCOM spec](https://www.khronos.org/registry/gles/extensions/QCOM/QCOM_tiled_rendering.txt) all those constants should be of type GLbitfield since both functions
```C
static void 	glEndTilingQCOM(GLbitfield preserveMask);
static void 	glStartTilingQCOM(GLuint x, GLuint y, GLuint width, GLuint height, GLbitfield preserveMask);
```
expects ``preserveMask`` as a GLbitfield. (also when looking at the constant values, it is obvious they all are bit-fields.

That should be it but I will do further testing. Thanks.

**Comment by ephja** [comment]
Only some of those clash with types, and the module does indeed compile, but maybe it should be discussed in a new issue/PR.

Thanks!

**Pull request merged**
